# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3rd.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_new1(object):
    def setupUi(self, new1):
        new1.setObjectName("new1")
        new1.resize(1366, 768)
        new1.setStyleSheet("background-image:url(i/pic1.jpg)")
        self.centralwidget = QtWidgets.QWidget(new1)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(450, 10, 201, 61))
        self.label.setStyleSheet("font: 75 48pt \"Pristina\";\n"
"background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 150, 171, 21))
        self.label_3.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 50, 121, 21))
        self.label_2.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 210, 171, 21))
        self.label_4.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(390, 150, 31, 21))
        self.label_5.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(390, 210, 31, 21))
        self.label_6.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 90, 171, 21))
        self.label_7.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(190, 390, 171, 21))
        self.label_9.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(190, 420, 171, 21))
        self.label_10.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(190, 120, 171, 21))
        self.label_11.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(190, 240, 171, 21))
        self.label_12.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(190, 180, 171, 21))
        self.label_13.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(190, 270, 171, 21))
        self.label_14.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(190, 360, 171, 21))
        self.label_15.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(390, 120, 31, 21))
        self.label_8.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(390, 240, 31, 21))
        self.label_16.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(390, 390, 31, 21))
        self.label_17.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(390, 360, 31, 21))
        self.label_18.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(390, 270, 31, 21))
        self.label_19.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(390, 180, 31, 21))
        self.label_20.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(390, 90, 31, 21))
        self.label_21.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(190, 320, 101, 21))
        self.label_22.setStyleSheet("font: 75 18pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(390, 540, 31, 21))
        self.label_23.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(390, 480, 31, 21))
        self.label_24.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(390, 510, 31, 21))
        self.label_25.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(390, 660, 31, 21))
        self.label_26.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(390, 630, 31, 21))
        self.label_27.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(390, 450, 31, 21))
        self.label_28.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(390, 420, 31, 21))
        self.label_29.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(190, 450, 171, 21))
        self.label_30.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(190, 540, 171, 21))
        self.label_31.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(190, 630, 171, 21))
        self.label_32.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(190, 480, 171, 21))
        self.label_33.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(190, 510, 171, 21))
        self.label_34.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(190, 590, 81, 21))
        self.label_35.setStyleSheet("font: 75 18pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(190, 660, 171, 21))
        self.label_36.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_36.setObjectName("label_36")
    #    self.label_37 = QtWidgets.QLabel(self.centralwidget)
     #   self.label_37.setGeometry(QtCore.QRect(190, 690, 171, 21))
      #  self.label_37.setStyleSheet("font: 16pt \"Pristina\";\n"
#"background-color: rgb(255, 255, 255);")
 #       self.label_37.setObjectName("label_37")
  #      self.label_38 = QtWidgets.QLabel(self.centralwidget)
 #       self.label_38.setGeometry(QtCore.QRect(390, 690, 31, 21))
   #     self.label_38.setStyleSheet("font: 16pt \"Pristina\";\n"
#"background-color: rgb(255, 255, 255);")
  #      self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(390, 720, 31, 21))
        self.label_39.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_39.setObjectName("label_39")
   #     self.label_40 = QtWidgets.QLabel(self.centralwidget)
  #      self.label_40.setGeometry(QtCore.QRect(190, 720, 171, 21))
 #       self.label_40.setStyleSheet("font: 16pt \"Pristina\";\n"
#"background-color: rgb(255, 255, 255);")
#        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(710, 50, 171, 21))
        self.label_41.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(710, 120, 171, 21))
        self.label_42.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(710, 270, 171, 21))
        self.label_43.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(710, 240, 171, 21))
        self.label_44.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(710, 180, 171, 21))
        self.label_45.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(710, 210, 171, 21))
        self.label_46.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(710, 150, 171, 21))
        self.label_47.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(910, 90, 31, 21))
        self.label_48.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(910, 120, 31, 21))
        self.label_49.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(910, 150, 31, 21))
        self.label_50.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(910, 180, 31, 21))
        self.label_51.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(910, 210, 31, 21))
        self.label_52.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(910, 240, 31, 21))
        self.label_53.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(710, 90, 181, 21))
        self.label_54.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(910, 270, 31, 21))
        self.label_55.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(710, 320, 171, 21))
        self.label_56.setStyleSheet("font: 75 18pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(710, 360, 171, 21))
        self.label_57.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.centralwidget)
        self.label_58.setGeometry(QtCore.QRect(710, 390, 171, 21))
        self.label_58.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.centralwidget)
        self.label_59.setGeometry(QtCore.QRect(710, 420, 171, 21))
        self.label_59.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(710, 450, 171, 21))
        self.label_60.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.centralwidget)
        self.label_61.setGeometry(QtCore.QRect(710, 480, 171, 21))
        self.label_61.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.centralwidget)
        self.label_62.setGeometry(QtCore.QRect(710, 510, 171, 21))
        self.label_62.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.centralwidget)
        self.label_63.setGeometry(QtCore.QRect(710, 540, 171, 21))
        self.label_63.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.centralwidget)
        self.label_64.setGeometry(QtCore.QRect(910, 360, 31, 21))
        self.label_64.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.centralwidget)
        self.label_65.setGeometry(QtCore.QRect(910, 390, 31, 21))
        self.label_65.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.centralwidget)
        self.label_66.setGeometry(QtCore.QRect(910, 420, 31, 21))
        self.label_66.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.centralwidget)
        self.label_67.setGeometry(QtCore.QRect(910, 450, 31, 21))
        self.label_67.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.centralwidget)
        self.label_68.setGeometry(QtCore.QRect(910, 480, 31, 21))
        self.label_68.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.centralwidget)
        self.label_69.setGeometry(QtCore.QRect(910, 510, 31, 21))
        self.label_69.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.centralwidget)
        self.label_70.setGeometry(QtCore.QRect(910, 540, 31, 21))
        self.label_70.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.centralwidget)
        self.label_71.setGeometry(QtCore.QRect(710, 590, 71, 21))
        self.label_71.setStyleSheet("font: 75 18pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.centralwidget)
        self.label_72.setGeometry(QtCore.QRect(710, 630, 171, 21))
        self.label_72.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.centralwidget)
        self.label_73.setGeometry(QtCore.QRect(710, 660, 171, 21))
        self.label_73.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(100, 255, 255);")
        self.label_73.setObjectName("label_73")
        #self.label_74 = QtWidgets.QLabel(self.centralwidget)
        #self.label_74.setGeometry(QtCore.QRect(710, 720, 171, 21))
        #self.label_74.setStyleSheet("font: 16pt \"Pristina\";\n"
#"background-color: rgb(255, 255, 255);")
   #     self.label_74.setObjectName("label_74")
    #    self.label_75 = QtWidgets.QLabel(self.centralwidget)
     #   self.label_75.setGeometry(QtCore.QRect(710, 690, 171, 21))
      #  self.label_75.setStyleSheet("font: 16pt \"Pristina\";\n"
#"background-color: rgb(255, 255, 255);")
 #       self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.centralwidget)
        self.label_76.setGeometry(QtCore.QRect(910, 630, 31, 21))
        self.label_76.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.centralwidget)
        self.label_77.setGeometry(QtCore.QRect(910, 660, 31, 21))
        self.label_77.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_77.setObjectName("label_77")
       # self.label_78 = QtWidgets.QLabel(self.centralwidget)
        #self.label_78.setGeometry(QtCore.QRect(910, 690, 31, 21))
        #self.label_78.setStyleSheet("font: 16pt \"Pristina\";\n"
#"background-color: rgb(255, 255, 255);")
 #       self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.centralwidget)
        self.label_79.setGeometry(QtCore.QRect(910, 720, 31, 21))
        self.label_79.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_79.setObjectName("label_79")
        new1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(new1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1091, 21))
        self.menubar.setObjectName("menubar")
        new1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(new1)
        self.statusbar.setObjectName("statusbar")
        new1.setStatusBar(self.statusbar)
        self.bttn_exit = QtWidgets.QPushButton(new1)
        self.bttn_exit.setGeometry(1250, 650, 75, 41)
        self.bttn_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bttn_exit.setMouseTracking(True)
        self.bttn_exit.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")

        self.retranslateUi(new1)
        self.bttn_exit.clicked.connect(new1.close)
        QtCore.QMetaObject.connectSlotsByName(new1)

    def retranslateUi(self, new1):
        _translate = QtCore.QCoreApplication.translate
        new1.setWindowTitle(_translate("new1", "MENU"))
        self.label.setText(_translate("new1", "MENU"))
        self.label_3.setText(_translate("new1", "Apple Juice"))
        self.label_2.setText(_translate("new1", "BEVERAGES"))
        self.label_4.setText(_translate("new1", "Soft Drinks"))
        self.label_5.setText(_translate("new1", "100"))
        self.label_6.setText(_translate("new1", "60"))
        self.label_7.setText(_translate("new1", "Cocktails"))
        self.label_9.setText(_translate("new1", "Bruschetta Carbonara"))
        self.label_10.setText(_translate("new1", "Chicken Wings"))
        self.label_11.setText(_translate("new1", "Smoothie"))
        self.label_12.setText(_translate("new1", "Lime Water"))
        self.label_13.setText(_translate("new1", "Shakes"))
        self.label_14.setText(_translate("new1", "Mineral Water"))
        self.label_15.setText(_translate("new1", "Bruschetta Tomato"))
        self.label_8.setText(_translate("new1", "140"))
        self.label_16.setText(_translate("new1", "50"))
        self.label_17.setText(_translate("new1", "275"))
        self.label_18.setText(_translate("new1", "290"))
        self.label_19.setText(_translate("new1", "45"))
        self.label_20.setText(_translate("new1", "90"))
        self.label_21.setText(_translate("new1", "250"))
        self.label_22.setText(_translate("new1", "SNAKES"))
        self.label_23.setText(_translate("new1", "110"))
        self.label_24.setText(_translate("new1", "150"))
        self.label_25.setText(_translate("new1", "140"))
        self.label_26.setText(_translate("new1", "250"))
        self.label_27.setText(_translate("new1", "275"))
        self.label_28.setText(_translate("new1", "240"))
        self.label_29.setText(_translate("new1", "260"))
        self.label_30.setText(_translate("new1", "Sausage Spring Roll"))
        self.label_31.setText(_translate("new1", "Salted French Fries"))
        self.label_32.setText(_translate("new1", "Chicken Soup"))
        self.label_33.setText(_translate("new1", "Garlic Bread"))
        self.label_34.setText(_translate("new1", "cheesy French Fries"))
        self.label_35.setText(_translate("new1", "SOUPS"))
        self.label_36.setText(_translate("new1", "Chicken Noodle Soup"))
        #self.label_37.setText(_translate("new1", "Chinese Soup"))
        #self.label_38.setText(_translate("new1", "230"))
        self.label_39.setText(_translate("new1", "180"))
       # self.label_40.setText(_translate("new1", "Veg Soup"))
        self.label_41.setText(_translate("new1", "SANDWICHES"))
        self.label_42.setText(_translate("new1", "Chicken Sandwich"))
        self.label_43.setText(_translate("new1", "Corn Sandwich"))
        self.label_44.setText(_translate("new1", "Egg Sandwich"))
        self.label_45.setText(_translate("new1", "Veg. Sandwich"))
        self.label_46.setText(_translate("new1", "NON Veg. Sandwich"))
        self.label_47.setText(_translate("new1", "Cheese Sandwich"))
        self.label_48.setText(_translate("new1", "200"))
        self.label_49.setText(_translate("new1", "180"))
        self.label_50.setText(_translate("new1", "160"))
        self.label_51.setText(_translate("new1", "140"))
        self.label_52.setText(_translate("new1", "120"))
        self.label_53.setText(_translate("new1", "100"))
        self.label_54.setText(_translate("new1", "Grilled Sandwich"))
        self.label_55.setText(_translate("new1", "80"))
        self.label_56.setText(_translate("new1", "PIZZA MANIA "))
        self.label_57.setText(_translate("new1", "Non veg. PIZZA"))
        self.label_58.setText(_translate("new1", "Veg. PIZZA"))
        self.label_59.setText(_translate("new1", "Margherita PIZZA"))
        self.label_60.setText(_translate("new1", "Bread PIZZA"))
        self.label_61.setText(_translate("new1", " BBQ PIZZA"))
        self.label_62.setText(_translate("new1", "Special PIZZA"))
        self.label_63.setText(_translate("new1", "Loaded Veg. PIZZA"))
        self.label_64.setText(_translate("new1", "380"))
        self.label_65.setText(_translate("new1", "280"))
        self.label_66.setText(_translate("new1", "150"))
        self.label_67.setText(_translate("new1", "100"))
        self.label_68.setText(_translate("new1", "350"))
        self.label_69.setText(_translate("new1", "400"))
        self.label_70.setText(_translate("new1", "350"))
        self.label_71.setText(_translate("new1", "PASTA"))
        self.label_72.setText(_translate("new1", "Red Sauce Pasta"))
        self.label_73.setText(_translate("new1", "White Sauce Pasta"))
        #self.label_74.setText(_translate("new1", "Spl. Pasta"))
        #self.label_75.setText(_translate("new1", "Veg. Pasta"))
        self.label_76.setText(_translate("new1", "150"))
        self.label_77.setText(_translate("new1", "140"))
        #self.label_78.setText(_translate("new1", "100"))
        self.label_79.setText(_translate("new1", "170"))
        self.bttn_exit.setText(_translate("new1","Back"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new1 = QtWidgets.QMainWindow()
    ui = Ui_new1()
    ui.setupUi(new1)
    new1.show()
    sys.exit(app.exec_())

